# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 377)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(6, 6, 581, 181))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("Screenshot from 2022-05-21 01-26-17.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.first = QtWidgets.QPushButton(self.centralwidget)
        self.first.setGeometry(QtCore.QRect(160, 210, 89, 25))
        self.first.setObjectName("first")
        self.second = QtWidgets.QPushButton(self.centralwidget)
        self.second.setGeometry(QtCore.QRect(340, 210, 89, 25))
        self.second.setObjectName("second")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.first.clicked.connect(self.show_first)
        self.second.clicked.connect(self.show_second)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.first.setText(_translate("MainWindow", "first"))
        self.second.setText(_translate("MainWindow", "second"))


    def show_first(self):
        self.photo.setPixmap(QtGui.QPixmap("Screenshot from 2022-05-21 01-26-17.png"))

    def show_second(self):
        self.photo.setPixmap(QtGui.QPixmap("Screenshot from 2023-11-18 19-51-47.png"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
